### ISSUE TITLE
Tensorflow backend crashes on null values

### ISSUE THREAD

**Issue by mmjb** [51alg/TerpreT#2]
I've tried running the updated NFP examples with the current TerpreT version and ended up crashing bin/fp_train:

    TerpreT$ bin/fp_train.py compiled/tensorflow_models/cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.hypers_compiled.py data/nfp/mapAddK__cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.data.json
    Construct forward graph... done in 28.66s.
    Construct gradient graph... done in 77.75s.
    Construct apply gradient graph... done in 0.27s.
    Construct check numerics graph... done in 46.82s.
    Initializing variables... done in 19.83s.
    {'dirichletInitScale': 2,
     'fEntropyBonusDecayRate': 0.5,
     'fGradientNoise': 0.01,
     'fGradientNoiseGamma': 0.55,
     'gradientClipC2': 1.0,
     'learning_rate': 0.1,
     'learning_rate_decay': 0.9,
     'minibatch_size': -1,
     'momentum': 0.0,
     'num_epochs': 3000,
     'optimizer': 'rmsprop',
     'print_frequency': 100,
     'stop_below_loss': 0.005}
    Traceback (most recent call last):
      File "bin/fp_train.py", line 62, in <module>
        train.load_and_run(args, FPTrainer)
      File "/mnt/nfs/users/mabrocks/Projects/TerpreT/bin/train.py", line 109, in load_and_run
        print_final_loss_breakdown=print_loss_breakdown)
      File "bin/../lib/trainer.py", line 452, in train
        self.do_one_update(train_batch_name)
      File "bin/../lib/trainer.py", line 279, in do_one_update
        results = self.sess.run(ops_to_execute, observed_vals)
      File "/mnt/nfs/users/mabrocks/venvs/fpsynth/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
        run_metadata_ptr)
      File "/mnt/nfs/users/mabrocks/venvs/fpsynth/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 943, in _run
        % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
    ValueError: Cannot feed value of shape (5,) for Tensor u'Tile_1:0', which has shape '(?, ?)'

I've attached a zip with the hypers + input examples causing this.

[mapAddK__cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.data.zip](https://github.com/51alg/TerpreT/files/1218284/mapAddK__cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.data.zip)

**Comment by jfeser** [comment]
Yeah, I'm seeing this as well. It's something to do with lines 92-98 in trainer.py. Not sure what they're doing though. Non array variables in the training data seem to trigger the bug.

**Comment by 51alg** [comment]
After this fix I get:

```
bin$ python fp_train.py compiled/tensorflow_models/cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.hypers_compiled.py ../data/bug1/mapAddK__cmbtypimm__maxInt_10__inputNum_2__inputStackSize_5__prefixLength_0__lambdaLength_3__suffixLength_2.data.json
Construct forward graph... done in 26.02s.
Construct gradient graph... done in 70.39s.
Construct apply gradient graph... done in 0.24s.
Initializing variables... done in 12.93s.
{'dirichletInitScale': 2,
 'fEntropyBonusDecayRate': 0.5,
 'fGradientNoise': 0.01,
 'fGradientNoiseGamma': 0.55,
 'gradientClipC2': 1.0,
 'learning_rate': 0.1,
 'learning_rate_decay': 0.9,
 'minibatch_size': -1,
 'momentum': 0.0,
 'num_epochs': 3000,
 'optimizer': 'rmsprop',
 'print_frequency': 100,
 'stop_below_loss': 0.005}
epoch 100, loss 0.099445, needed 26.36s
epoch 200, loss 0.0126155, needed 16.20s
epoch 300, loss 0.0072164, needed 16.14s
epoch 400, loss 0.00872865, needed 16.08s
epoch 500, loss 0.00946382, needed 16.09s
epoch 600, loss 0.00564517, needed 16.08s
epoch 700, loss 0.00775366, needed 16.15s
  Early training termination after 783 epochs because loss 0.004640 is below bound 0.005000.
Training stopped after 247s.
```
So it seems to work now
